Add rolling update

diff --git a/.github/workflows/main.workflow.yml b/.github/workflows/main.workflow.yml
--- a/.github/workflows/main.workflow.yml
+++ b/.github/workflows/main.workflow.yml
@@ -6,8 +6,6 @@ name: Deployment Pipeline
 on:
   push:
     branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
 
 jobs:
   test:
@@ -113,6 +111,20 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           args: --sarif-file-output=snyk.sarif --file=./whiteboard-service.sln
+          
+        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test
+        run: snyk code test --sarif > snyk-code.sarif --file=./whiteboard-service.sln || true
+
+        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+      - name: Snyk Open Source monitor
+        run: snyk monitor --file=./whiteboard-service.sln
+
+        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+        # Use || true to not fail the pipeline.
+      - name: Snyk IaC test and report
+        run: snyk iac test --report --file=./whiteboard-service.sln || true
 
         # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
@@ -120,21 +132,31 @@ jobs:
         with:
           sarif_file: snyk.sarif
 
-  Deploy:
+  push-image:
+    name: Push to ACR
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
     needs: [snyk-analysis]
-    if: ${{ github.event_name == 'push' }}
     steps:
       - run: echo 'The test workflow has passed, start deployment'
       - uses: actions/checkout@v4
-      - uses: azure/docker-login@v2
+
+      - name: 'Login via Azure CLI'
+        uses: azure/login@v2
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }} 
+
+      - name: 'Build and push image'
+        uses: azure/docker-login@v2
         with:
           login-server: ${{ secrets.ACR_LOGIN_SERVER }}
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
+      - run: |
+          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}
+          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}
 
       - name: build image
         uses: docker/setup-buildx-action@v3
@@ -146,3 +168,23 @@ jobs:
           file: ./Whiteboard.Service/Dockerfile
           push: true
           tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}
+
+  deploy-image:
+    name: Deploy update
+    needs: [push-image]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Login via Azure CLI
+        uses: azure/login@v2
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+      
+      - name: Get AKS credentials
+        run: az aks get-credentials -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_CLUSTER_NAME }}
+
+      - name: Restart deployment
+        run: kubectl rollout restart deployment/whiteboard-service
+        continue-on-error: true # If AKS cluster is not available, pipeline should not fail
